"""AI vs. Human PR classification logic."""
from .github_utils import GitHubUtils

class PRClassifier:
    """Classifies PRs as AI-generated or Human-written."""
    
    # Keywords indicating AI-generated content
    AI_KEYWORDS = [
        'chatgpt', 'gpt-4', 'gpt-3', 'gpt4', 'gpt3',
        'copilot', 'github copilot',
        'claude', 'anthropic',
        'gemini', 'bard',
        'llm', 'large language model',
        'ai generated', 'generated by ai', 'ai-generated',
        'machine learning', 'neural',
        'generated code', 'auto-generated',
        'code generated', 'automatically generated',
        'ai assistance', 'ai-assisted'
    ]
    
    # GitHub labels commonly used for AI-generated PRs
    AI_LABELS = [
        'ai-generated', 'ai generated',
        'copilot',
        'gpt', 'gpt-generated',
        'llm', 'llm-generated',
        'bot', 'automated',
        'generated by ai', 'ai-assisted'
    ]
    
    # Common bot account patterns
    BOT_PATTERNS = [
        'bot', 'github-actions', 'dependabot', 'renovate',
        'snyk', 'coveralls', 'codecov'
    ]
    
    def __init__(self):
        """Initialize classifier."""
        self.github_utils = GitHubUtils()
    
    def classify_pr(self, pr):
        """
        Classify a PR as AI or Human.
        
        Args:
            pr: github.PullRequest.PullRequest object
        
        Returns:
            dict: {
                'classification': 'AI' | 'Human',
                'confidence': float (0-1),
                'signals': list of detection methods,
                'details': dict with raw signals
            }
        """
        metadata = self.github_utils.get_pr_metadata(pr)
        
        # Check for AI signals
        label_signal = self._check_labels(metadata['labels'])
        text_signal = self._check_text_content(
            metadata['title'] + ' ' + metadata['body']
        )
        author_signal = self._check_author_patterns(metadata['author'])
        
        # Aggregate signals
        signals = []
        confidence = 0.0
        
        if label_signal:
            signals.append('ai_label')
            confidence += 0.4
        
        if text_signal:
            signals.append('ai_keywords')
            confidence += 0.35
        
        if author_signal:
            signals.append('bot_author')
            confidence += 0.25
        
        # Normalize confidence
        confidence = min(confidence, 1.0)
        
        # Classify: threshold 0.3 for AI
        classification = 'AI' if confidence >= 0.3 else 'Human'
        
        return {
            'classification': classification,
            'confidence': round(confidence, 2),
            'signals': signals,
            'details': {
                'label_signal': label_signal,
                'text_signal': text_signal,
                'author_signal': author_signal
            }
        }
    
    def _check_labels(self, labels):
        """Check if PR labels indicate AI content."""
        labels_lower = [l.lower() for l in labels]
        for label in labels_lower:
            for ai_label in self.AI_LABELS:
                if ai_label in label:
                    return True
        return False
    
    def _check_text_content(self, text):
        """Check if PR title/body contains AI keywords."""
        text_lower = text.lower()
        for keyword in self.AI_KEYWORDS:
            if keyword in text_lower:
                return True
        return False
    
    def _check_author_patterns(self, author):
        """Check if author matches bot account patterns."""
        author_lower = author.lower()
        for pattern in self.BOT_PATTERNS:
            if pattern in author_lower:
                return True
        return False
    
    def extract_timestamp_model(self, pr_created_date):
        """
        Infer which AI model era based on PR creation date.
        
        Returns:
            dict: {'era': str, 'approx_model': str}
        """
        year_month = pr_created_date.strftime('%Y-%m')
        
        # Known release dates (approximate)
        if pr_created_date.year < 2022:
            return {'era': 'pre-copilot', 'approx_model': 'N/A'}
        elif pr_created_date.year == 2022:
            return {'era': 'copilot-v1', 'approx_model': 'Copilot (Codex)'}
        elif pr_created_date.year == 2023:
            if pr_created_date.month <= 6:
                return {'era': 'copilot-v1-late', 'approx_model': 'Copilot + GPT-4'}
            else:
                return {'era': 'copilot-v2', 'approx_model': 'Copilot (GPT-4)'}
        elif pr_created_date.year == 2024:
            return {'era': 'copilot-v2-cursor', 'approx_model': 'Copilot v2 / Cursor'}
        else:
            return {'era': 'current', 'approx_model': 'Copilot v2+ / Claude / Gemini'}