import os
import time
from github import Github, RateLimitExceededException
from dotenv import load_dotenv
import pandas as pd

# Load environment variables
load_dotenv()
TOKEN = os.getenv("GITHUB_TOKEN")

# Initialize PyGithub (Handles auth & retries better than raw requests)
g = Github(TOKEN)

def check_ai_rules(repo):
    """
    Scans project documentation for keywords indicating mandatory AI tagging.
    Returns: bool (True if rules detected), list (matched keywords)
    """
    rule_keywords = ["ai generated", "generated by ai", "copilot tag", "gpt tag", "llm tag"]
    found_rules = []
    
    # Files to check for rules
    docs = ["README.md", "CONTRIBUTING.md", "docs/CONTRIBUTING.md", ".github/CONTRIBUTING.md"]
    
    for doc_path in docs:
        try:
            # Fetch file content
            content = repo.get_contents(doc_path).decoded_content.decode('utf-8').lower()
            for phrase in rule_keywords:
                if phrase in content:
                    found_rules.append(phrase)
        except:
            continue # File doesn't exist, skip
            
    return len(found_rules) > 0, list(set(found_rules))

def filter_repository(repo):
    """
    Applies proposal filters using PyGithub objects.
    """
    try:
        # 1. Activity Filter: Check merged PRs in last year
        # Note: 'closed' includes merged. We filter for merged status below.
        pulls = repo.get_pulls(state='closed', sort='updated', direction='desc')
        
        merged_count = 0
        ai_pr_count = 0
        ai_labels = ['ai-generated', 'copilot', 'gpt', 'bot']
        
        # Check the last 100 closed PRs (optimization: don't check all history yet)
        for pr in pulls[:100]: 
            if pr.merged:
                merged_count += 1
                
                # Check for AI labels
                pr_labels = [l.name.lower() for l in pr.labels]
                if any(lbl in text for lbl in ai_labels for text in pr_labels):
                    ai_pr_count += 1
        
        if merged_count < 50:
            return False, merged_count, ai_pr_count, []

        # 2. Rules Check (New Feature)
        has_rules, rules = check_ai_rules(repo)
        
        # Relaxed criteria: Accept if high AI PR count OR explicit rules found
        if ai_pr_count >= 10 or has_rules:
            return True, merged_count, ai_pr_count, rules
            
        return False, merged_count, ai_pr_count, rules

    except Exception as e:
        print(f"Error filtering {repo.full_name}: {e}")
        return False, 0, 0, []

def main(target_count=20):
    discovered_repos = []
    
    # Expanded Search Query: Python repos, pushed recently, sorted by help-wanted or stars
    # "is:public" is implicit but good for clarity
    query = "language:python stars:>200 pushed:>2024-01-01"
    
    print(f"Searching GitHub with query: {query}")
    
    try:
        repositories = g.search_repositories(query=query, sort="stars", order="desc")
        
        for repo in repositories:
            if len(discovered_repos) >= target_count:
                break
                
            print(f"Checking {repo.full_name}...", end=" ")
            
            is_valid, merged, ai_count, rules = filter_repository(repo)
            
            if is_valid:
                print(f"MATCH! (Merged: {merged}, AI-PRs: {ai_count}, Rules: {rules})")
                discovered_repos.append({
                    "full_name": repo.full_name,
                    "url": repo.html_url,
                    "merged_prs_checked": merged,
                    "ai_prs_found": ai_count,
                    "explicit_ai_rules": rules
                })
            else:
                print(f"Skipped. (Merged: {merged}, AI-PRs: {ai_count})")
                
            # Sleep to be nice to API (PyGithub handles core rate limits, but search is stricter)
            time.sleep(2)

    except RateLimitExceededException:
        print("Hit GitHub Rate Limit. Try again later.")

    # Save results
    df = pd.DataFrame(discovered_repos)
    os.makedirs('data/raw', exist_ok=True)
    df.to_csv('data/raw/targeted_repos.csv', index=False)
    print(f"\nSaved {len(discovered_repos)} repositories to data/raw/targeted_repos.csv")

if __name__ == "__main__":
    main()